---
abstract: 'Generate a monthly calendar in PostScript'
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires:
  FindBin: 0
  Module::Build: 0.21
  Test::More: 0
configure_requires:
  Module::Build: 0.21
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PostScript-Calendar
no_index:
  directory:
    - tools
recommends:
  Astro::MoonPhase: 0.60
requires:
  Date::Calc: 5.0
  PostScript::File: 2.01
  perl: 5.8.0
resources:
  repository: http://github.com/madsen/postscript-calendar
version: 0.05
